import 'antd/dist/antd.css'; 


import Head from 'next/head'
import Image from 'next/image'
import { getAllPublicPost } from '../lib/posts'
import styles from '../styles/Home.module.css'


export async function getStaticProps() {
  const allPost = await getAllPublicPost();
  console.log('async:', allPost);
  return {
    props: allPost.data
  };
}

export default function Home(props) {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Blog test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>Navbar here</nav>

      <main>
        {console.log(props)}
        <h2>List of all post</h2>
        {props.results.map(postData => (
          
          <>
            {console.log(postData)}
            <h3>{postData.title}</h3>
          </>
        ))
        }
      </main>

      
    </div>
  )
}
