# Generated by Django 3.2.4 on 2021-06-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255)),
                ('option_value', models.TextField()),
            ],
            options={
                'db_table': 'blog_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_comment_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'comment_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('paragraph_index', models.IntegerField()),
                ('type', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'paragraph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField()),
                ('create_date', models.TextField()),
                ('raw_post_content', models.TextField()),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'post_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReactMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_type', models.IntegerField()),
                ('member_type', models.IntegerField()),
                ('location_type', models.IntegerField()),
                ('accepted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'react_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReactNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('state', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'react_need',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.IntegerField()),
            ],
            options={
                'db_table': 'react_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryRelationship',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='members.post')),
            ],
            options={
                'db_table': 'category_relationship',
                'managed': False,
            },
        ),
    ]
